### ISSUE TITLE
Error launching app

### ISSUE THREAD

**Issue by notorioushanz** [1PhoenixM/avior-service#3]
I'm on mac os x 10.10.3.
I've followed the getting started instruction. But after "sails lift" i have this Error :

info: Starting app...

/Users/beatminer/Infra-Ops/Floodlight/avior-service/node_modules/bcrypt/node_modules/bindings/bindings.js:79
        throw e
              ^
Error: dlopen(/Users/beatminer/Infra-Ops/Floodlight/avior-service/node_modules/bcrypt/build/Release/bcrypt_lib.node, 1): no suitable image found.  Did find:
    /Users/beatminer/Infra-Ops/Floodlight/avior-service/node_modules/bcrypt/build/Release/bcrypt_lib.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/Users/beatminer/Infra-Ops/Floodlight/avior-service/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/Users/beatminer/Infra-Ops/Floodlight/avior-service/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by notorioushanz** [comment]
Jus re-reading what i've pasted i just did "npm install bcrypt"
Seems to work now.
