### ISSUE TITLE
Avior falling

### ISSUE THREAD

**Issue by Neby1992** [1PhoenixM/avior-service#4]
Hi,
I have problem with FloodLight 0.90 - 1.2, when I try to push flow, I got this 

avior-service/api/adapters/FloodlightAdapter.js:366
            if(innerArr.constructor === Array && innerArr.length > 1){
                       ^
TypeError: Cannot read property 'constructor' of undefined
    at Object.module.exports.dpidParse (/home/petr/Plocha/avior-service/api/adapters/FloodlightAdapter.js:366:15)
    at IncomingMessage.<anonymous> (/home/petr/Plocha/avior-service/toClient.js:180:54)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)

**Comment by Neby1992** [comment]
I changeg obj,port to obj.port_reply in FloodlightAdapter.js on line 365 and it works.
