### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by OriginalOgre** [1PhoenixM/avior-service#5]
I downloaded Avior 2.0 per the instructions (as well as dependencies) but when I execute "sails lift" I get "Error: Module did not self-register" (stack trace provided below).  I am using Ubuntu 14.04, Node v5.10.0 and Sails v0.12.2.  I do not claim to be a JS Guru so I was hoping this might be quick fix and you could point me in the right direction.

Thanks

/home/sdn/avior-service/node_modules/bcrypt/node_modules/bindings/bindings.js:79
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at bindings (/home/sdn/avior-service/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/home/sdn/avior-service/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by 1PhoenixM** [comment]
Hi,

For now, maybe this helps?
http://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register

Thanks!
